// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/adam.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Script execution
type ScriptRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScriptPath     string                 `protobuf:"bytes,1,opt,name=script_path,json=scriptPath,proto3" json:"script_path,omitempty"`
	Args           []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env            map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Profile        string                 `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScriptRequest) Reset() {
	*x = ScriptRequest{}
	mi := &file_proto_adam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptRequest) ProtoMessage() {}

func (x *ScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptRequest.ProtoReflect.Descriptor instead.
func (*ScriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_adam_proto_rawDescGZIP(), []int{0}
}

func (x *ScriptRequest) GetScriptPath() string {
	if x != nil {
		return x.ScriptPath
	}
	return ""
}

func (x *ScriptRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ScriptRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ScriptRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *ScriptRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	TimedOut      bool                   `protobuf:"varint,4,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptResponse) Reset() {
	*x = ScriptResponse{}
	mi := &file_proto_adam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptResponse) ProtoMessage() {}

func (x *ScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptResponse.ProtoReflect.Descriptor instead.
func (*ScriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_adam_proto_rawDescGZIP(), []int{1}
}

func (x *ScriptResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ScriptResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ScriptResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ScriptResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

// Path validation
type PathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"` // "read", "write", "execute"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathRequest) Reset() {
	*x = PathRequest{}
	mi := &file_proto_adam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRequest) ProtoMessage() {}

func (x *PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRequest.ProtoReflect.Descriptor instead.
func (*PathRequest) Descriptor() ([]byte, []int) {
	return file_proto_adam_proto_rawDescGZIP(), []int{2}
}

func (x *PathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PathRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type PathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	ResolvedPath  string                 `protobuf:"bytes,2,opt,name=resolved_path,json=resolvedPath,proto3" json:"resolved_path,omitempty"`
	DenialReason  string                 `protobuf:"bytes,3,opt,name=denial_reason,json=denialReason,proto3" json:"denial_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathResponse) Reset() {
	*x = PathResponse{}
	mi := &file_proto_adam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathResponse) ProtoMessage() {}

func (x *PathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathResponse.ProtoReflect.Descriptor instead.
func (*PathResponse) Descriptor() ([]byte, []int) {
	return file_proto_adam_proto_rawDescGZIP(), []int{3}
}

func (x *PathResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *PathResponse) GetResolvedPath() string {
	if x != nil {
		return x.ResolvedPath
	}
	return ""
}

func (x *PathResponse) GetDenialReason() string {
	if x != nil {
		return x.DenialReason
	}
	return ""
}

// Profile management
type ProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileRequest) Reset() {
	*x = ProfileRequest{}
	mi := &file_proto_adam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRequest) ProtoMessage() {}

func (x *ProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileRequest.ProtoReflect.Descriptor instead.
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_adam_proto_rawDescGZIP(), []int{4}
}

type SetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileName   string                 `protobuf:"bytes,1,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProfileRequest) Reset() {
	*x = SetProfileRequest{}
	mi := &file_proto_adam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProfileRequest) ProtoMessage() {}

func (x *SetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProfileRequest.ProtoReflect.Descriptor instead.
func (*SetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_adam_proto_rawDescGZIP(), []int{5}
}

func (x *SetProfileRequest) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_proto_adam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_adam_proto_rawDescGZIP(), []int{6}
}

func (x *ProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Status
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_adam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_adam_proto_rawDescGZIP(), []int{7}
}

type StatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RuntimeHealthy   bool                   `protobuf:"varint,1,opt,name=runtime_healthy,json=runtimeHealthy,proto3" json:"runtime_healthy,omitempty"`
	ActiveContainers int32                  `protobuf:"varint,2,opt,name=active_containers,json=activeContainers,proto3" json:"active_containers,omitempty"`
	CurrentProfile   string                 `protobuf:"bytes,3,opt,name=current_profile,json=currentProfile,proto3" json:"current_profile,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_adam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_adam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_adam_proto_rawDescGZIP(), []int{8}
}

func (x *StatusResponse) GetRuntimeHealthy() bool {
	if x != nil {
		return x.RuntimeHealthy
	}
	return false
}

func (x *StatusResponse) GetActiveContainers() int32 {
	if x != nil {
		return x.ActiveContainers
	}
	return 0
}

func (x *StatusResponse) GetCurrentProfile() string {
	if x != nil {
		return x.CurrentProfile
	}
	return ""
}

var File_proto_adam_proto protoreflect.FileDescriptor

const file_proto_adam_proto_rawDesc = "" +
	"\n" +
	"\x10proto/adam.proto\x12\x04adam\"\xef\x01\n" +
	"\rScriptRequest\x12\x1f\n" +
	"\vscript_path\x18\x01 \x01(\tR\n" +
	"scriptPath\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12.\n" +
	"\x03env\x18\x03 \x03(\v2\x1c.adam.ScriptRequest.EnvEntryR\x03env\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x0eScriptResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12\x1b\n" +
	"\ttimed_out\x18\x04 \x01(\bR\btimedOut\"?\n" +
	"\vPathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\"r\n" +
	"\fPathResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12#\n" +
	"\rresolved_path\x18\x02 \x01(\tR\fresolvedPath\x12#\n" +
	"\rdenial_reason\x18\x03 \x01(\tR\fdenialReason\"\x10\n" +
	"\x0eProfileRequest\"6\n" +
	"\x11SetProfileRequest\x12!\n" +
	"\fprofile_name\x18\x01 \x01(\tR\vprofileName\"%\n" +
	"\x0fProfileResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x0f\n" +
	"\rStatusRequest\"\x8f\x01\n" +
	"\x0eStatusResponse\x12'\n" +
	"\x0fruntime_healthy\x18\x01 \x01(\bR\x0eruntimeHealthy\x12+\n" +
	"\x11active_containers\x18\x02 \x01(\x05R\x10activeContainers\x12'\n" +
	"\x0fcurrent_profile\x18\x03 \x01(\tR\x0ecurrentProfile2\xb4\x02\n" +
	"\x0eRuntimeService\x12:\n" +
	"\rExecuteScript\x12\x13.adam.ScriptRequest\x1a\x14.adam.ScriptResponse\x125\n" +
	"\fValidatePath\x12\x11.adam.PathRequest\x1a\x12.adam.PathResponse\x129\n" +
	"\n" +
	"GetProfile\x12\x14.adam.ProfileRequest\x1a\x15.adam.ProfileResponse\x12<\n" +
	"\n" +
	"SetProfile\x12\x17.adam.SetProfileRequest\x1a\x15.adam.ProfileResponse\x126\n" +
	"\tGetStatus\x12\x13.adam.StatusRequest\x1a\x14.adam.StatusResponseB\x1fZ\x1dgithub.com/adam/runtime/protob\x06proto3"

var (
	file_proto_adam_proto_rawDescOnce sync.Once
	file_proto_adam_proto_rawDescData []byte
)

func file_proto_adam_proto_rawDescGZIP() []byte {
	file_proto_adam_proto_rawDescOnce.Do(func() {
		file_proto_adam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_adam_proto_rawDesc), len(file_proto_adam_proto_rawDesc)))
	})
	return file_proto_adam_proto_rawDescData
}

var file_proto_adam_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_adam_proto_goTypes = []any{
	(*ScriptRequest)(nil),     // 0: adam.ScriptRequest
	(*ScriptResponse)(nil),    // 1: adam.ScriptResponse
	(*PathRequest)(nil),       // 2: adam.PathRequest
	(*PathResponse)(nil),      // 3: adam.PathResponse
	(*ProfileRequest)(nil),    // 4: adam.ProfileRequest
	(*SetProfileRequest)(nil), // 5: adam.SetProfileRequest
	(*ProfileResponse)(nil),   // 6: adam.ProfileResponse
	(*StatusRequest)(nil),     // 7: adam.StatusRequest
	(*StatusResponse)(nil),    // 8: adam.StatusResponse
	nil,                       // 9: adam.ScriptRequest.EnvEntry
}
var file_proto_adam_proto_depIdxs = []int32{
	9, // 0: adam.ScriptRequest.env:type_name -> adam.ScriptRequest.EnvEntry
	0, // 1: adam.RuntimeService.ExecuteScript:input_type -> adam.ScriptRequest
	2, // 2: adam.RuntimeService.ValidatePath:input_type -> adam.PathRequest
	4, // 3: adam.RuntimeService.GetProfile:input_type -> adam.ProfileRequest
	5, // 4: adam.RuntimeService.SetProfile:input_type -> adam.SetProfileRequest
	7, // 5: adam.RuntimeService.GetStatus:input_type -> adam.StatusRequest
	1, // 6: adam.RuntimeService.ExecuteScript:output_type -> adam.ScriptResponse
	3, // 7: adam.RuntimeService.ValidatePath:output_type -> adam.PathResponse
	6, // 8: adam.RuntimeService.GetProfile:output_type -> adam.ProfileResponse
	6, // 9: adam.RuntimeService.SetProfile:output_type -> adam.ProfileResponse
	8, // 10: adam.RuntimeService.GetStatus:output_type -> adam.StatusResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_adam_proto_init() }
func file_proto_adam_proto_init() {
	if File_proto_adam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_adam_proto_rawDesc), len(file_proto_adam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_adam_proto_goTypes,
		DependencyIndexes: file_proto_adam_proto_depIdxs,
		MessageInfos:      file_proto_adam_proto_msgTypes,
	}.Build()
	File_proto_adam_proto = out.File
	file_proto_adam_proto_goTypes = nil
	file_proto_adam_proto_depIdxs = nil
}
