# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import adam_pb2 as adam__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in adam_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeServiceStub(object):
    """Core Runtime Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteScript = channel.unary_unary(
                '/adam.RuntimeService/ExecuteScript',
                request_serializer=adam__pb2.ScriptRequest.SerializeToString,
                response_deserializer=adam__pb2.ScriptResponse.FromString,
                _registered_method=True)
        self.ValidatePath = channel.unary_unary(
                '/adam.RuntimeService/ValidatePath',
                request_serializer=adam__pb2.PathRequest.SerializeToString,
                response_deserializer=adam__pb2.PathResponse.FromString,
                _registered_method=True)
        self.GetProfile = channel.unary_unary(
                '/adam.RuntimeService/GetProfile',
                request_serializer=adam__pb2.ProfileRequest.SerializeToString,
                response_deserializer=adam__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.SetProfile = channel.unary_unary(
                '/adam.RuntimeService/SetProfile',
                request_serializer=adam__pb2.SetProfileRequest.SerializeToString,
                response_deserializer=adam__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/adam.RuntimeService/GetStatus',
                request_serializer=adam__pb2.StatusRequest.SerializeToString,
                response_deserializer=adam__pb2.StatusResponse.FromString,
                _registered_method=True)


class RuntimeServiceServicer(object):
    """Core Runtime Service
    """

    def ExecuteScript(self, request, context):
        """Execute a script in a sandboxed container
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePath(self, request, context):
        """Validate if a path can be accessed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfile(self, request, context):
        """Get current security profile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProfile(self, request, context):
        """Set active security profile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get runtime status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteScript': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteScript,
                    request_deserializer=adam__pb2.ScriptRequest.FromString,
                    response_serializer=adam__pb2.ScriptResponse.SerializeToString,
            ),
            'ValidatePath': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePath,
                    request_deserializer=adam__pb2.PathRequest.FromString,
                    response_serializer=adam__pb2.PathResponse.SerializeToString,
            ),
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=adam__pb2.ProfileRequest.FromString,
                    response_serializer=adam__pb2.ProfileResponse.SerializeToString,
            ),
            'SetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProfile,
                    request_deserializer=adam__pb2.SetProfileRequest.FromString,
                    response_serializer=adam__pb2.ProfileResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=adam__pb2.StatusRequest.FromString,
                    response_serializer=adam__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adam.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('adam.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """Core Runtime Service
    """

    @staticmethod
    def ExecuteScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam.RuntimeService/ExecuteScript',
            adam__pb2.ScriptRequest.SerializeToString,
            adam__pb2.ScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidatePath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam.RuntimeService/ValidatePath',
            adam__pb2.PathRequest.SerializeToString,
            adam__pb2.PathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam.RuntimeService/GetProfile',
            adam__pb2.ProfileRequest.SerializeToString,
            adam__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam.RuntimeService/SetProfile',
            adam__pb2.SetProfileRequest.SerializeToString,
            adam__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adam.RuntimeService/GetStatus',
            adam__pb2.StatusRequest.SerializeToString,
            adam__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
