# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: adam.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'adam.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nadam.proto\x12\x04\x61\x64\x61m\"\xb3\x01\n\rScriptRequest\x12\x13\n\x0bscript_path\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\x12)\n\x03\x65nv\x18\x03 \x03(\x0b\x32\x1c.adam.ScriptRequest.EnvEntry\x12\x0f\n\x07profile\x18\x04 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\x05 \x01(\x05\x1a*\n\x08\x45nvEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"V\n\x0eScriptResponse\x12\x11\n\texit_code\x18\x01 \x01(\x05\x12\x0e\n\x06stdout\x18\x02 \x01(\t\x12\x0e\n\x06stderr\x18\x03 \x01(\t\x12\x11\n\ttimed_out\x18\x04 \x01(\x08\".\n\x0bPathRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\"M\n\x0cPathResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x15\n\rresolved_path\x18\x02 \x01(\t\x12\x15\n\rdenial_reason\x18\x03 \x01(\t\"\x10\n\x0eProfileRequest\")\n\x11SetProfileRequest\x12\x14\n\x0cprofile_name\x18\x01 \x01(\t\"\x1f\n\x0fProfileResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x0f\n\rStatusRequest\"]\n\x0eStatusResponse\x12\x17\n\x0fruntime_healthy\x18\x01 \x01(\x08\x12\x19\n\x11\x61\x63tive_containers\x18\x02 \x01(\x05\x12\x17\n\x0f\x63urrent_profile\x18\x03 \x01(\t2\xb4\x02\n\x0eRuntimeService\x12:\n\rExecuteScript\x12\x13.adam.ScriptRequest\x1a\x14.adam.ScriptResponse\x12\x35\n\x0cValidatePath\x12\x11.adam.PathRequest\x1a\x12.adam.PathResponse\x12\x39\n\nGetProfile\x12\x14.adam.ProfileRequest\x1a\x15.adam.ProfileResponse\x12<\n\nSetProfile\x12\x17.adam.SetProfileRequest\x1a\x15.adam.ProfileResponse\x12\x36\n\tGetStatus\x12\x13.adam.StatusRequest\x1a\x14.adam.StatusResponseB\x1fZ\x1dgithub.com/adam/runtime/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adam_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035github.com/adam/runtime/proto'
  _globals['_SCRIPTREQUEST_ENVENTRY']._loaded_options = None
  _globals['_SCRIPTREQUEST_ENVENTRY']._serialized_options = b'8\001'
  _globals['_SCRIPTREQUEST']._serialized_start=21
  _globals['_SCRIPTREQUEST']._serialized_end=200
  _globals['_SCRIPTREQUEST_ENVENTRY']._serialized_start=158
  _globals['_SCRIPTREQUEST_ENVENTRY']._serialized_end=200
  _globals['_SCRIPTRESPONSE']._serialized_start=202
  _globals['_SCRIPTRESPONSE']._serialized_end=288
  _globals['_PATHREQUEST']._serialized_start=290
  _globals['_PATHREQUEST']._serialized_end=336
  _globals['_PATHRESPONSE']._serialized_start=338
  _globals['_PATHRESPONSE']._serialized_end=415
  _globals['_PROFILEREQUEST']._serialized_start=417
  _globals['_PROFILEREQUEST']._serialized_end=433
  _globals['_SETPROFILEREQUEST']._serialized_start=435
  _globals['_SETPROFILEREQUEST']._serialized_end=476
  _globals['_PROFILERESPONSE']._serialized_start=478
  _globals['_PROFILERESPONSE']._serialized_end=509
  _globals['_STATUSREQUEST']._serialized_start=511
  _globals['_STATUSREQUEST']._serialized_end=526
  _globals['_STATUSRESPONSE']._serialized_start=528
  _globals['_STATUSRESPONSE']._serialized_end=621
  _globals['_RUNTIMESERVICE']._serialized_start=624
  _globals['_RUNTIMESERVICE']._serialized_end=932
# @@protoc_insertion_point(module_scope)
